baseURL = "https://algus.ninja/"
languageCode = "es-MX"
title = "Algus' Blog"

disableKinds = ["taxonomy", "term"]
staticDir = ["static", "content/notes/attachments"]
enableGitInfo = false
disableAliases = true

# Ignore the attachments so we don't have double attachments
ignoreFiles = ["content/notes/attachments", "obsidian.css", "obsidian-templates/.*"]

[permalinks]
  notes = "/:filename"

[params]
  description = "Un lugar lleno de hipervínculos que podrían llevarte a lugares interesantes."
  notesPath = "/notes"
  [params.time]
    RFC3339 = "2006-01-02T15:04:05Z07:00"
    default = "January 2, 2006"
    short = "02 Jan 2006"

[minify]
  disableSVG = true

[build]
  writeStats = true

[markup.goldmark.renderer]
  unsafe = true